apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-client-deployment
  labels:
    app: voting-app
    tier: frontend
spec:
  replicas: 0 
  selector:
    matchLabels:
      app: voting-app
      component: client
  template:
    metadata:
      labels:
        app: voting-app
        component: client
    spec:
      containers:
      - name: client
        image: joaquinpicazo/votesys_client:client-latest 