apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-server-ingress
  labels:
    app: voting-app
    tier: networking
  annotations:
    #networking.k8s.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: voting-server-service 
            port:
              number: 65432