apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-server-ingress
  labels:
    app: voting-app
spec:
  rules:
  - host: voto.k8s.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voting-server-service
            port:
              number: 65432