apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-server
  labels:
    app: voting-app
    tier: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: voting-app
      component: server
  template:
    metadata:
      labels:
        app: voting-app
        component: server
    spec:
      containers:
      - name: server
        image: joaquinpicazo/votesys_server:server-latest 
        ports:
        - containerPort: 65432
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
